"""Visualization utility functions.

Provides general visualization helper functions, such as figure saving and style configuration.
"""

from pathlib import Path

import matplotlib.pyplot as plt


def get_default_output_dir() -> Path:
    """Get the default output directory.

    Returns:
        Path object pointing to the output/figures directory
    """
    return Path(__file__).resolve().parents[2] / "output" / "figures"


def get_figsize_from_pt(
    width_pt: float, ratio: float = 1.618, fraction: float = 1.0
) -> tuple[float, float]:
    r"""Convert LaTeX width (pt) to Matplotlib figsize (inches).

    Parameters:
        width_pt: LaTeX \columnwidth or \textwidth in points (pt),
                  use \typeout{COLUMNWIDTH = \the\columnwidth}
                  or \typeout{TEXTWIDTH = \the\textwidth} to obtain
        ratio: Aspect ratio (width/height), default golden ratio 1.618
        fraction: Fraction of width to use (e.g., 0.95 for margins)

    Returns:
        (width_inch, height_inch): Matplotlib figure dimensions in inches

    Note:
        1 inch = 25.4 mm
               = 72.27 pt   (TeX pt)
               = 72 bp      (PostScript / PDF / Word / matplotlib / MATLAB pt)

        -------------------------------------------------------------------
        Original comment from matplotlib.backends.backend_pdf:

        It's better to use only one unit for all coordinates, since the
        arithmetic in latex seems to produce inaccurate conversions.

        latex_pt_to_in = 1. / 72.27
        latex_in_to_pt = 1. / latex_pt_to_in
        mpl_pt_to_in = 1. / 72.
        mpl_in_to_pt = 1. / mpl_pt_to_in
        -------------------------------------------------------------------

        A4 (210 * 297 mm)
        = 8.27 * 11.69 inch
        ≈ 598 * 845 pt (TeX pt)

        Letter (216 * 279 mm)
        = 8.5 * 11 inch
        ≈ 615 * 795 pt (TeX pt)
    """
    inches_per_pt = 1 / 72.27  # latex_pt_to_in
    width_inch = width_pt * inches_per_pt * fraction
    height_inch = width_inch / ratio
    return (width_inch, height_inch)


def setup_paper_style(
    textwidth: float,
    ratio: float,
    fraction: float,
    font_size_tex: float = 10,
    font_size_main: float = 9,
    line_width_axis: float = 0.5,
) -> None:
    """Set up paper-style plotting configuration.

    Args:
        textwidth: LaTeX text width (pt), used to determine figure dimensions
        ratio: Figure aspect ratio (width/height)
        fraction: Fraction of width to use
        font_size_tex: LaTeX font size for axis labels, etc.
        font_size_main: Main font size for tick labels, etc.
        line_width_axis: Axis line width
    """
    figsize = get_figsize_from_pt(textwidth, ratio, fraction)

    plt.rcParams.update(
        {
            "figure.figsize": figsize,
            # Journal Standard: Arial/Helvetica.
            # Note:
            # - Draw.io's default Helvetica is effectively Arial.
            # - On Linux systems, Arial may not be available.
            "font.family": "sans-serif",
            "font.sans-serif": [
                "Arial",
                "Helvetica",
                "DejaVu Sans",
            ],
            "font.size": font_size_main,
            "axes.labelsize": font_size_tex,  # Use the same font size as the main text.
            "axes.titlesize": font_size_tex,  # Unused: Titles are generated by LaTeX \caption{}
            "axes.linewidth": line_width_axis,  # <= 0.8
            "axes.grid": True,
            "xtick.labelsize": font_size_main,
            "xtick.major.size": 5 * 0.45 * line_width_axis,
            "xtick.major.width": 0.45 * line_width_axis,
            "xtick.major.pad": 0.15 * font_size_main,
            "ytick.labelsize": font_size_main,
            "ytick.major.size": 5 * 0.45 * line_width_axis,
            "ytick.major.width": 0.45 * line_width_axis,
            "ytick.major.pad": 0.15 * font_size_main,
            "grid.linestyle": "--",
            "grid.color": "#bdbdbd",
            "grid.linewidth": 0.35 * line_width_axis,
            "grid.alpha": 0.3,  # Transparency
            "lines.linewidth": 1.8 * line_width_axis,
            "lines.markersize": 3.3 * 1.8 * line_width_axis,  # linear
            "legend.fontsize": font_size_main,
            "legend.frameon": True,
            "legend.fancybox": True,
            "legend.framealpha": 0.6,
            "legend.edgecolor": "#bdbdbd",
            "patch.linewidth": line_width_axis,
            "savefig.dpi": 600,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0,
        }
    )


def save_figure(
    filename: str,
    output_dir: Path | None = None,
    extensions: list[str] | None = None,
    verbose: bool = True,
    fig: plt.Figure | None = None,
) -> list[Path]:
    """Save figure to file.

    Args:
        filename: Filename without extension
        output_dir: Output directory, uses default if None
        extensions: List of formats to save, defaults to ["pdf", "png"]
        verbose: Whether to print save information
        fig: Matplotlib figure object, uses current active figure (plt.gcf()) if None

    Returns:
        List of saved file paths

    Example:
        >>> save_figure("loss_curve")
        [PosixPath('.../loss_curve.pdf'), PosixPath('.../loss_curve.png')]

        >>> save_figure("my_plot", extensions=["svg"])
        [PosixPath('.../my_plot.svg')]

        >>> fig, ax = plt.subplots()
        >>> save_figure("custom", fig=fig)
        [PosixPath('.../custom.pdf'), PosixPath('.../custom.png')]
    """
    if output_dir is None:
        base_output_dir = get_default_output_dir()
    else:
        base_output_dir = output_dir

    if extensions is None:
        extensions = ["pdf", "png"]

    # Use current active figure if fig is not provided
    if fig is None:
        fig = plt.gcf()

    saved_paths = []
    for ext in extensions:
        dir_path = base_output_dir / ext
        dir_path.mkdir(parents=True, exist_ok=True)
        output_path = dir_path / f"{filename}.{ext}"

        if verbose:
            print(f"Saving figure to: {output_path}")

        fig.savefig(output_path)
        saved_paths.append(output_path)

    return saved_paths
